import * as XLSX from 'xlsx'
import { PDFDocument, rgb, StandardFonts, degrees } from 'pdf-lib'
import JSZip from 'jszip'

const WATERMARK_TEXT = [
  'Generated by ExcelfromPDF (Free Plan)',
  '',
  'Upgrade to Pro to remove this watermark and unlock:',
  '  • Unlimited conversions',
  '  • Unlimited file size',
  '  • Advanced OCR engine',
  '  • Advanced table formatting',
  '  • Priority support',
  '',
  'Visit: excelfrom.pdf/pricing',
]

export async function addWatermarkToExcel(blob: Blob): Promise<Blob> {
  const arrayBuffer = await blob.arrayBuffer()
  const workbook = XLSX.read(arrayBuffer, { type: 'array' })

  const ws = XLSX.utils.aoa_to_sheet(WATERMARK_TEXT.map((line) => [line]))
  ws['!cols'] = [{ wch: 55 }]
  XLSX.utils.book_append_sheet(workbook, ws, 'ExcelfromPDF')

  const output = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' })
  return new Blob([output], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

export async function addWatermarkToPdf(blob: Blob): Promise<Blob> {
  const arrayBuffer = await blob.arrayBuffer()
  const pdfDoc = await PDFDocument.load(arrayBuffer)
  const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const pages = pdfDoc.getPages()

  for (const page of pages) {
    const { width, height } = page.getSize()

    // Diagonal watermark stamp
    page.drawText('ExcelfromPDF FREE', {
      x: width / 2 - 120,
      y: height / 2,
      size: 42,
      font,
      color: rgb(0.75, 0.75, 0.75),
      opacity: 0.35,
      rotate: degrees(45),
    })

    // Footer note
    page.drawText('Free plan • Upgrade at excelfrom.pdf/pricing to remove watermark', {
      x: 20,
      y: 12,
      size: 7,
      font,
      color: rgb(0.6, 0.6, 0.6),
      opacity: 0.8,
    })
  }

  const pdfBytes = await pdfDoc.save()
  return new Blob([pdfBytes.buffer as ArrayBuffer], { type: 'application/pdf' })
}

export async function addWatermarkToZip(blob: Blob): Promise<Blob> {
  const zip = await JSZip.loadAsync(await blob.arrayBuffer())
  const outZip = new JSZip()

  const fileEntries = Object.entries(zip.files).filter(([, f]) => !f.dir)

  await Promise.all(
    fileEntries.map(async ([name, file]) => {
      const data = await file.async('arraybuffer')
      const lowerName = name.toLowerCase()

      if (lowerName.endsWith('.xlsx') || lowerName.endsWith('.xls')) {
        const watermarked = await addWatermarkToExcel(new Blob([data]))
        const watermarkedBuffer = await watermarked.arrayBuffer()
        outZip.file(name, watermarkedBuffer)
      } else if (lowerName.endsWith('.pdf')) {
        const watermarked = await addWatermarkToPdf(new Blob([data]))
        const watermarkedBuffer = await watermarked.arrayBuffer()
        outZip.file(name, watermarkedBuffer)
      } else {
        outZip.file(name, data)
      }
    })
  )

  const outBlob = await outZip.generateAsync({ type: 'blob' })
  return outBlob
}
